//
//  Installer+Compute.swift
//  Asspp
//
//  Created by 秋星桥 on 2024/7/11.
//

import ApplePackage
import Foundation

extension Installer {
    var plistEndpoint: URL {
        var comps = URLComponents()
        comps.scheme = "https"
        comps.host = Self.sni
        comps.path = "/\(id).plist"
        comps.port = port
        return comps.url!
    }

    /// The payload is served over plain HTTP on the loopback interface. The
    /// system installer accepts an http:// package URL as long as the manifest
    /// itself came over publicly trusted HTTPS, which `manifestEndpoint` provides.
    var payloadEndpoint: URL {
        var comps = URLComponents()
        comps.scheme = "http"
        comps.host = "127.0.0.1"
        comps.path = "/\(id).ipa"
        comps.port = port
        return comps.url!
    }

    /// The manifest is generated by a public HTTPS service instead of being
    /// served locally. The on-device installer daemon fetches the manifest with
    /// the system trust store only, so a user-installed mkcert root (the old
    /// `plistEndpoint` route) leaves it stuck at "Preparing to install" on
    /// current iOS. Same approach as Feather's "Semi Local" server mode.
    var manifestEndpoint: URL {
        var comps = URLComponents(url: Self.manifestServiceURL, resolvingAgainstBaseURL: false)!
        comps.queryItems = [
            URLQueryItem(name: "bundleid", value: archive.software.bundleID),
            URLQueryItem(name: "name", value: archive.software.name),
            URLQueryItem(name: "version", value: archive.software.version),
            URLQueryItem(name: "fetchurl", value: payloadEndpoint.absoluteString),
        ]
        return comps.url!
    }

    var iTunesLink: URL {
        // Encode the nested URL fully so the itms-services parser cannot split
        // on the manifest service's own query string.
        let encoded = manifestEndpoint.absoluteString
            .addingPercentEncoding(withAllowedCharacters: .alphanumerics)!
        return URL(string: "itms-services://?action=download-manifest&url=\(encoded)")!
    }

    var displayImageSmallEndpoint: URL {
        var comps = URLComponents()
        comps.scheme = "https"
        comps.host = Self.sni
        comps.path = "/app57x57.png"
        comps.port = port
        return comps.url!
    }

    var displayImageSmallData: Data {
        createWhite(57)
    }

    var displayImageLargeEndpoint: URL {
        var comps = URLComponents()
        comps.scheme = "https"
        comps.host = Self.sni
        comps.path = "/app512x512.png"
        comps.port = port
        return comps.url!
    }

    var displayImageLargeData: Data {
        createWhite(512)
    }

    var indexHtml: String {
        """
        <html> <head> <meta http-equiv="refresh" content="0;url=\(iTunesLink.absoluteString)"> </head> </html>
        """
    }

    var installManifest: [String: Any] {
        [
            "items": [
                [
                    "assets": [
                        [
                            "kind": "software-package",
                            "url": payloadEndpoint.absoluteString,
                        ],
                        [
                            "kind": "display-image",
                            "url": displayImageSmallEndpoint.absoluteString,
                        ],
                        [
                            "kind": "full-size-image",
                            "url": displayImageLargeEndpoint.absoluteString,
                        ],
                    ],
                    "metadata": [
                        "bundle-identifier": archive.software.bundleID,
                        "bundle-version": archive.software.version,
                        "kind": "software",
                        "title": archive.software.name,
                    ],
                ],
            ],
        ]
    }

    var installManifestData: Data {
        (try? PropertyListSerialization.data(
            fromPropertyList: installManifest,
            format: .xml,
            options: .zero,
        )) ?? .init()
    }
}
